[[cells]]
name = "omni_lock"
enable_type_id = true
location = { file = "cells/omni_lock" }

[[cells]]
name = "simple_udt"
enable_type_id = true
location = { file = "cells/simple_udt" }

[[cells]]
name = "seck256k1_data"
enable_type_id = false
location = { tx_hash = "0xe6caa05213b22b780cd7e17ae192c94cd2e89d5b7ea218ec3a4760302b99d5ab", index = 3 }

[[dep_groups]]
name = "omni_lock_dep_group"
cells = [ "omni_lock", "seck256k1_data" ]

# The lock script set to output cells
[lock]
code_hash = "0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8"
args = "0x6a81512944f7fa5ef1c40cdbcff58353b60b4bea"
hash_type = "type"

# For unlocking inputs with multisig lock script
[multisig_config]
sighash_addresses = [
  "ckt1qyq829u0x32fchlfe5dqc4awh5q70h0eyj0qh8ngj4",
  "ckt1qyq283mcnqwpncwuccglkgfjmnd2cp662pjqykjl03",
]
require_first_n = 0
threshold = 1
