[[cells]]
name = "always_success"
enable_type_id = true
location = { file = "always_success" }

[[dep_groups]]
name = "always_success_dep_group"
cells = []

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x75178f34549c5fe9cd1a0c57aebd01e7ddf9249e"
hash_type = "type"
